import { InlineNodeRenderer } from './inline-node-renderer';
import { Asciidoctor } from '@asciidoctor/core';
import Inline = Asciidoctor.Inline;

export class InlineResourceRenderer extends InlineNodeRenderer<Inline> {
  ignoredAttributeNames = ['default-alt'];
  positionalAttributes = [{ name: 'alt', position: 1 }];

  render(node: Inline): string {
    const type = node.getType();
    const innerAttributes = this.getNonDefaultAttributes(node)
      .filter(it => !isAutoGeneratedAlt(it.name, node));
    const content = this.renderAttributes(innerAttributes);
    return `${type}:${node.getTarget()}[${content}]`;
  }
}

function isAutoGeneratedAlt(name, node: Inline): boolean {
  return name === 'alt' && node.getAttribute('default-alt') === node.getAttribute('alt');
}

