import { InlineNodeRenderer } from './inline-node-renderer';
import { InlineNode } from '../dom/inline-node';

export class InlineResourceRenderer extends InlineNodeRenderer<InlineNode> {
  ignoredAttributeNames = ['default-alt'];
  positionalAttributes = [{ name: 'alt', position: 1 }];

  render(node: InlineNode): string {
    const type = node.getType();
    const innerAttributes = this.getNonDefaultAttributes(node)
      .filter(it => !isAutoGeneratedAlt(it.name, node));
    const content = this.renderAttributes(innerAttributes);
    return `${type}:${node.getTarget()}[${content}]`;
  }
}

function isAutoGeneratedAlt(name, node: InlineNode): boolean {
  return name === 'alt' && node.getAttribute('default-alt') === node.getAttribute('alt');
}

