import { AdocNode } from './adoc-node';
import { InlineNodeRenderer } from './inline-node-renderer';

interface InlineResourceNode extends AdocNode {
  getTarget(): string;
}

export class InlineResourceRenderer extends InlineNodeRenderer<InlineResourceNode> {
  ignoredAttributeNames = ['default-alt'];
  positionalAttributes = [{ name: 'alt', position: 1 }];

  render(node: InlineResourceNode): string {
    const type = node.getType();
    const innerAttributes = this.getNonDefaultAttributes(node)
      .filter(({ name, value }) => !isAutoGeneratedAlt(name, node));
    const content = this.renderAttributes(innerAttributes);
    return `${type}:${node.getTarget()}[${content}]`;
  }
}

function isAutoGeneratedAlt(name, node: InlineResourceNode): boolean {
  return name === 'alt' && node.getAttribute('default-alt') === node.getAttribute('alt');
}

